# 📓 Session 1: PyTorch Tensors – Basics
#### Author: PRIYANSHU K. GUPTA 🚀

# 🚀 What’s a Tensor?

 A tensor is just a multi-dimensional array, like:
 * 1D → vector (e.g., [1, 2, 3])
 * 2D → matrix (e.g., [[1, 2], [3, 4]])
 * 3D+ → used for images, videos, audio, etc.

 In PyTorch, tensors are like NumPy arrays but with GPU support 💪

In [1]:
import torch

# ⚙️ Check PyTorch version
print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.7.1+cpu


In [3]:
# 🧱 1. Creating Tensors

# Scalar (0D)
scalar = torch.tensor(5)
print("\n🔹 Scalar:\n", scalar)
print("Shape:", scalar.shape)
print("Type:", scalar.dtype)

# Vector (1D)
vector = torch.tensor([1.0, 2.0, 3.0])
print("\n🔹 Vector:\n", vector)

# Matrix (2D)
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("\n🔹 Matrix:\n", matrix)

# Tensor (3D)
tensor3d = torch.randn(2, 3, 4)
print("\n🔹 3D Tensor:\n", tensor3d)


🔹 Scalar:
 tensor(5)
Shape: torch.Size([])
Type: torch.int64

🔹 Vector:
 tensor([1., 2., 3.])

🔹 Matrix:
 tensor([[1., 2.],
        [3., 4.]])

🔹 3D Tensor:
 tensor([[[ 0.1854, -0.3776,  1.6905, -0.7923],
         [-2.0667, -1.2677, -0.2489,  1.6181],
         [-0.4217, -2.0052,  0.5474,  0.7723]],

        [[ 0.7171,  1.6132, -0.6967, -0.1878],
         [-0.8830,  1.1567, -0.5219,  0.0782],
         [ 1.0139,  0.1732,  0.7319, -0.4477]]])


In [4]:
# 📐 2. Tensor Attributes
print("\n✅ Tensor Attributes:")
print("Shape:", tensor3d.shape)
print("Datatype:", tensor3d.dtype)
print("Device:", tensor3d.device)


✅ Tensor Attributes:
Shape: torch.Size([2, 3, 4])
Datatype: torch.float32
Device: cpu


In [5]:
# 🔁 3. Tensor Operations

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("\n🔧 Basic Ops:")
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

print("\n📍 Dot Product:", torch.dot(a, b))
print("📏 Mean:", torch.mean(a))
print("💠 Matrix Multiplication:\n", torch.matmul(matrix, matrix.T))


🔧 Basic Ops:
Addition: tensor([5., 7., 9.])
Subtraction: tensor([-3., -3., -3.])
Multiplication: tensor([ 4., 10., 18.])
Division: tensor([0.2500, 0.4000, 0.5000])

📍 Dot Product: tensor(32.)
📏 Mean: tensor(2.)
💠 Matrix Multiplication:
 tensor([[ 5., 11.],
        [11., 25.]])


In [6]:
# 🔄 4. Reshaping Tensors

x = torch.arange(9)
print("\n🔄 Original Tensor:", x)

reshaped = x.view(3, 3)
print("Reshaped (3x3):\n", reshaped)

flattened = reshaped.flatten()
print("Flattened:", flattened)


🔄 Original Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Reshaped (3x3):
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Flattened: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [7]:
# 🖥️ 5. Using GPU (if available)

if torch.cuda.is_available():
    print("\n🔥 CUDA is available! Moving tensor to GPU.")
    vector_gpu = vector.to('cuda')
    print("Tensor on GPU:", vector_gpu)
else:
    print("\n⚠️ CUDA not available. Running on CPU.")


⚠️ CUDA not available. Running on CPU.


In [8]:
# 🧪 6. Mini Practice Task

print("\n🧪 Task: Create 4x4 tensor and calculate mean & flatten")

mat = torch.randn(4, 4)
print("Random Matrix:\n", mat)
print("Mean along dim=0:", mat.mean(dim=0))
print("Mean along dim=1:", mat.mean(dim=1))
print("Flattened:", mat.flatten())


🧪 Task: Create 4x4 tensor and calculate mean & flatten
Random Matrix:
 tensor([[-0.3466, -0.2883,  1.3362, -0.0751],
        [ 0.2694,  0.1599,  0.3189,  0.9459],
        [ 1.3293, -1.9539,  0.0970, -0.6835],
        [-0.8377, -0.8055,  0.4814,  0.3511]])
Mean along dim=0: tensor([ 0.1036, -0.7220,  0.5584,  0.1346])
Mean along dim=1: tensor([ 0.1565,  0.4235, -0.3028, -0.2027])
Flattened: tensor([-0.3466, -0.2883,  1.3362, -0.0751,  0.2694,  0.1599,  0.3189,  0.9459,
         1.3293, -1.9539,  0.0970, -0.6835, -0.8377, -0.8055,  0.4814,  0.3511])
